Proyecto_CADI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cursos/', include('cursos.urls')),
    path('contacto/', include('contacto.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('anuncios/', include('anuncios.urls')),
    path('carro/', include('carro.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('', include('CADIApp.urls')),
]

carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path("agregar/<int:curso_id>/", views.agregar_curso, name="agregar"),
    path("eliminar/<int:curso_id>/", views.eliminar_curso, name="eliminar"),
    path("restar/<int:curso_id>/", views.restar_curso, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

cursos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('', views.cursos, name="Cursos"),
]

carro/models.py
from django.db import models

# Create your models here.

cursos/models.py
from django.db import models

#Create your models here

class CategoriaCursos(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='categoriaCursos'
        verbose_name_plural='categoriasCursos'

    def __str__(self):
        return self.nombre

class Cursos(models.Model):
    nombre=models.CharField(max_length=50)
    categoria=models.ForeignKey(CategoriaCursos, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="cursos", null=True, blank=True)
    precio=models.FloatField()
    descripcion=models.CharField(max_length=150)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='curso'
        verbose_name_plural='cursos'

carro/views.py
from django.shortcuts import render, redirect

from .carro import Carro

from cursos.models import Cursos

# Create your views here.

def agregar_curso(request, curso_id):
    
    carro=Carro(request)

    curso=Cursos.objects.get(id=curso_id)

    carro.agregar(curso=curso)

    return redirect("Cursos")

def eliminar_curso(request, curso_id):
    
    carro=Carro(request)

    curso=Cursos.objects.get(id=curso_id)

    carro.eliminar(curso=curso)

    return redirect("Cursos")

def restar_curso(request, curso_id):
    
    carro=Carro(request)

    curso=Cursos.objects.get(id=curso_id)

    carro.restar(curso=curso)

    return redirect("Cursos")

def limpiar_carro(request, curso_id):
    
    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Cursos")

cursos/views.py
from django.shortcuts import render
from .models import Cursos

# Create your views here.

def cursos(request):

    cursos=Cursos.objects.all()

    return render(request, "cursos/cursos.html",{"cursos": cursos})

cursos/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>

        <tr>

            <th colspan="3" class="text-center">

                Incripciones

            </th>

        </tr>

        <tr>

            <th>Curso</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>

    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}

                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        <a href="{% url 'carro:agregar' value.curso_id%}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.curso_id%}" class="btn btn-sm btn-success">-</a>
                        <br>
                        {{value.precio}} $

                    </td>

                </tr>

            {% endfor %}
        {% else %}
            <tr>

                <td colspan="3">

                    <div class="alert alert-danger text-center">
                        NO se ha inscrito a ningún curso
                    </div>

                </td>

            </tr>
        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carro}} $

            </td>
        </tr>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align: center;">

                <a href="../inscripciones" class="btn btn-success">Inscribirse</a>

            </td>
        </tr>
        {% endif %}
    </tfoot>

</table>